baseURL = "https://dazhaoniel.github.io/danielsmovies/"
languageCode = "en-us"
title = "Daniel's Movie Reviews"
theme = "hyde"

[Params]
  Author = "Daniel Zhao"
  Description = "A list of movies I watched in 2017, with their original years and my reviews. "